// <auto-generated />
using System;
using AlphaCinema.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlphaCinema.Infrastructure.Migrations
{
    [DbContext(typeof(AlphaCinemaDbContext))]
    [Migration("20260325115810_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlphaCinema.Core.Entities.DanhGia", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_danh_gia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<int>("DiemSo")
                        .HasColumnType("int")
                        .HasColumnName("diem_so");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<int>("MaPhim")
                        .HasColumnType("int")
                        .HasColumnName("ma_phim");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaPhim");

                    b.ToTable("DanhGia", (string)null);
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.Ghe", b =>
                {
                    b.Property<int>("MaGhe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_ghe");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGhe"));

                    b.Property<string>("Hang")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("hang");

                    b.Property<string>("LoaiGhe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("loai_ghe");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int")
                        .HasColumnName("ma_phong");

                    b.Property<int>("SoGhe")
                        .HasColumnType("int")
                        .HasColumnName("so_ghe");

                    b.HasKey("MaGhe");

                    b.HasIndex("MaPhong");

                    b.ToTable("Ghe", (string)null);
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_hoa_don");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<int?>("MaKhuyenMai")
                        .HasColumnType("int")
                        .HasColumnName("ma_khuyen_mai");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<DateTime>("NgayGiaoDich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_giao_dich")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phuong_thuc_thanh_toan");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tong_tien");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaKhuyenMai");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.KhuyenMai", b =>
                {
                    b.Property<int>("MaKhuyenMai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_khuyen_mai");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhuyenMai"));

                    b.Property<decimal?>("DonHangToiThieu")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("don_hang_toi_thieu");

                    b.Property<decimal>("GiaTriGiam")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gia_tri_giam");

                    b.Property<decimal?>("GiamToiDa")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("giam_toi_da");

                    b.Property<string>("LoaiGiamGia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("loai_giam_gia");

                    b.Property<string>("MaCodeGiamGia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_code_giam_gia");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bat_dau");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("date")
                        .HasColumnName("ngay_ket_thuc");

                    b.Property<string>("TenKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_khuyen_mai");

                    b.HasKey("MaKhuyenMai");

                    b.ToTable("KhuyenMai", (string)null);
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<int>("DiemTichLuy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("diem_tich_luy");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ho_ten");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int")
                        .HasColumnName("ma_vai_tro");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mat_khau");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaVaiTro");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.Phim", b =>
                {
                    b.Property<int>("MaPhim")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_phim");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhim"));

                    b.Property<string>("Poster")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("poster");

                    b.Property<string>("TenPhim")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_phim");

                    b.Property<string>("TheLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("the_loai");

                    b.Property<int>("ThoiLuong")
                        .HasColumnType("int")
                        .HasColumnName("thoi_luong");

                    b.Property<string>("TomTat")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tom_tat");

                    b.Property<string>("TrangThaiPhim")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Sắp chiếu")
                        .HasColumnName("trang_thai_phim");

                    b.HasKey("MaPhim");

                    b.ToTable("Phim", (string)null);
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.PhongChieu", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_phong");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhong"));

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_phong");

                    b.HasKey("MaPhong");

                    b.ToTable("PhongChieu", (string)null);
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.SuatChieu", b =>
                {
                    b.Property<int>("MaSuatChieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_suat_chieu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSuatChieu"));

                    b.Property<string>("DinhDang")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("dinh_dang");

                    b.Property<decimal>("GiaVeGoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("gia_ve_goc");

                    b.Property<int>("MaPhim")
                        .HasColumnType("int")
                        .HasColumnName("ma_phim");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int")
                        .HasColumnName("ma_phong");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_gian_bat_dau");

                    b.HasKey("MaSuatChieu");

                    b.HasIndex("MaPhim");

                    b.HasIndex("MaPhong");

                    b.ToTable("SuatChieu", (string)null);
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_vai_tro");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_vai_tro");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTro", (string)null);

                    b.HasData(
                        new
                        {
                            MaVaiTro = 1,
                            TenVaiTro = "Admin"
                        },
                        new
                        {
                            MaVaiTro = 2,
                            TenVaiTro = "Staff"
                        },
                        new
                        {
                            MaVaiTro = 3,
                            TenVaiTro = "Customer"
                        });
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.Ve", b =>
                {
                    b.Property<int>("MaVe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_ve");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVe"));

                    b.Property<decimal>("GiaVe")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gia_ve");

                    b.Property<int>("MaGhe")
                        .HasColumnType("int")
                        .HasColumnName("ma_ghe");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int")
                        .HasColumnName("ma_hoa_don");

                    b.Property<string>("MaQR")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ma_qr");

                    b.Property<int>("MaSuatChieu")
                        .HasColumnType("int")
                        .HasColumnName("ma_suat_chieu");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaVe");

                    b.HasIndex("MaGhe");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaSuatChieu", "MaGhe")
                        .IsUnique();

                    b.ToTable("Ve", (string)null);
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.DanhGia", b =>
                {
                    b.HasOne("AlphaCinema.Core.Entities.NguoiDung", "NguoiDung")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlphaCinema.Core.Entities.Phim", "Phim")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaPhim")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("Phim");
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.Ghe", b =>
                {
                    b.HasOne("AlphaCinema.Core.Entities.PhongChieu", "PhongChieu")
                        .WithMany("Ghes")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhongChieu");
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.HoaDon", b =>
                {
                    b.HasOne("AlphaCinema.Core.Entities.KhuyenMai", "KhuyenMai")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKhuyenMai")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AlphaCinema.Core.Entities.NguoiDung", "NguoiDung")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhuyenMai");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.NguoiDung", b =>
                {
                    b.HasOne("AlphaCinema.Core.Entities.VaiTro", "VaiTro")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.SuatChieu", b =>
                {
                    b.HasOne("AlphaCinema.Core.Entities.Phim", "Phim")
                        .WithMany("SuatChieus")
                        .HasForeignKey("MaPhim")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlphaCinema.Core.Entities.PhongChieu", "PhongChieu")
                        .WithMany("SuatChieus")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Phim");

                    b.Navigation("PhongChieu");
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.Ve", b =>
                {
                    b.HasOne("AlphaCinema.Core.Entities.Ghe", "Ghe")
                        .WithMany("Ves")
                        .HasForeignKey("MaGhe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlphaCinema.Core.Entities.HoaDon", "HoaDon")
                        .WithMany("Ves")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlphaCinema.Core.Entities.SuatChieu", "SuatChieu")
                        .WithMany("Ves")
                        .HasForeignKey("MaSuatChieu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ghe");

                    b.Navigation("HoaDon");

                    b.Navigation("SuatChieu");
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.Ghe", b =>
                {
                    b.Navigation("Ves");
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.HoaDon", b =>
                {
                    b.Navigation("Ves");
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.KhuyenMai", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.NguoiDung", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.Phim", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("SuatChieus");
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.PhongChieu", b =>
                {
                    b.Navigation("Ghes");

                    b.Navigation("SuatChieus");
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.SuatChieu", b =>
                {
                    b.Navigation("Ves");
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
