// <auto-generated />
using System;
using AlphaCinema.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlphaCinema.Infrastructure.Migrations
{
    [DbContext(typeof(AlphaCinemaDbContext))]
    partial class AlphaCinemaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlphaCinema.Core.Entities.DanhGia", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_danh_gia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<int>("DiemSo")
                        .HasColumnType("int")
                        .HasColumnName("diem_so");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<int>("MaPhim")
                        .HasColumnType("int")
                        .HasColumnName("ma_phim");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaPhim");

                    b.ToTable("DanhGia", (string)null);
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.DoAnVat", b =>
                {
                    b.Property<int>("MaDoAnVat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_do_an_vat");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDoAnVat"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gia");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("hinh_anh");

                    b.Property<string>("Loai")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("loai");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_mon");

                    b.HasKey("MaDoAnVat");

                    b.ToTable("DoAnVat", (string)null);

                    b.HasData(
                        new
                        {
                            MaDoAnVat = 1,
                            Gia = 45000m,
                            HinhAnh = "/assets/concessions/bap_caramel_m.png",
                            Loai = "Bắp",
                            MoTa = "Bắp rang vị caramel thơm ngọt size vừa",
                            TenMon = "Bắp Rang Ngọt Caramel (M)"
                        },
                        new
                        {
                            MaDoAnVat = 2,
                            Gia = 55000m,
                            HinhAnh = "/assets/concessions/bap_caramel_m.png",
                            Loai = "Bắp",
                            MoTa = "Bắp rang vị caramel thơm ngọt size lớn",
                            TenMon = "Bắp Rang Ngọt Caramel (L)"
                        },
                        new
                        {
                            MaDoAnVat = 3,
                            Gia = 45000m,
                            HinhAnh = "/assets/concessions/bap_phomai_l.png",
                            Loai = "Bắp",
                            MoTa = "Bắp rang vị phô mai mặn mà size vừa",
                            TenMon = "Bắp Rang Phô Mai (M)"
                        },
                        new
                        {
                            MaDoAnVat = 4,
                            Gia = 55000m,
                            HinhAnh = "/assets/concessions/bap_phomai_l.png",
                            Loai = "Bắp",
                            MoTa = "Bắp rang vị phô mai mặn mà size lớn",
                            TenMon = "Bắp Rang Phô Mai (L)"
                        },
                        new
                        {
                            MaDoAnVat = 5,
                            Gia = 35000m,
                            HinhAnh = "/assets/concessions/coca_l.png",
                            Loai = "Nước",
                            MoTa = "Nước ngọt Coca Cola mát lạnh size lớn",
                            TenMon = "Coca Cola (L)"
                        },
                        new
                        {
                            MaDoAnVat = 6,
                            Gia = 35000m,
                            HinhAnh = "/assets/concessions/coca_l.png",
                            Loai = "Nước",
                            MoTa = "Nước ngọt Pepsi mát lạnh size lớn",
                            TenMon = "Pepsi (L)"
                        },
                        new
                        {
                            MaDoAnVat = 7,
                            Gia = 45000m,
                            HinhAnh = "/assets/concessions/cam_tuoi.png",
                            Loai = "Nước",
                            MoTa = "Nước cam ép nguyên chất giàu vitamin",
                            TenMon = "Nước Cam Tươi"
                        },
                        new
                        {
                            MaDoAnVat = 8,
                            Gia = 50000m,
                            HinhAnh = "/assets/concessions/milo_trachanh.png",
                            Loai = "Nước",
                            MoTa = "Thức uống sáng tạo kết hợp Milo và Trà xanh",
                            TenMon = "Milo Trà Xanh Đậu Đen"
                        },
                        new
                        {
                            MaDoAnVat = 9,
                            Gia = 75000m,
                            HinhAnh = "/assets/concessions/pizza_mini.png",
                            Loai = "Thức ăn",
                            MoTa = "Pizza cỡ nhỏ phủ xúc xích và phô mai",
                            TenMon = "Pizza Xúc Xích Mini"
                        },
                        new
                        {
                            MaDoAnVat = 10,
                            Gia = 75000m,
                            HinhAnh = "/assets/concessions/combo_single.png",
                            Loai = "Combo",
                            MoTa = "1 Bắp (M) + 1 Nước (L) - Tiết kiệm hơn",
                            TenMon = "Combo Single Alpha"
                        },
                        new
                        {
                            MaDoAnVat = 11,
                            Gia = 115000m,
                            HinhAnh = "/assets/concessions/combo_couple.png",
                            Loai = "Combo",
                            MoTa = "1 Bắp (L) + 2 Nước (L) - Cho cặp đôi",
                            TenMon = "Combo Couple Alpha"
                        });
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.Ghe", b =>
                {
                    b.Property<int>("MaGhe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_ghe");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGhe"));

                    b.Property<string>("Hang")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("hang");

                    b.Property<string>("LoaiGhe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("loai_ghe");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int")
                        .HasColumnName("ma_phong");

                    b.Property<int>("SoGhe")
                        .HasColumnType("int")
                        .HasColumnName("so_ghe");

                    b.HasKey("MaGhe");

                    b.HasIndex("MaPhong");

                    b.ToTable("Ghe", (string)null);
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_hoa_don");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<int?>("MaKhuyenMai")
                        .HasColumnType("int")
                        .HasColumnName("ma_khuyen_mai");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<string>("MaVaoCong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_vao_cong");

                    b.Property<DateTime>("NgayGiaoDich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_giao_dich")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phuong_thuc_thanh_toan");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tong_tien");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Đã thanh toán")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaKhuyenMai");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.HoaDonDoAnVat", b =>
                {
                    b.Property<int>("MaHoaDonDoAnVat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_hoa_don_do_an_vat");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDonDoAnVat"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("don_gia");

                    b.Property<int>("MaDoAnVat")
                        .HasColumnType("int")
                        .HasColumnName("ma_do_an_vat");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int")
                        .HasColumnName("ma_hoa_don");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("so_luong");

                    b.HasKey("MaHoaDonDoAnVat");

                    b.HasIndex("MaDoAnVat");

                    b.HasIndex("MaHoaDon");

                    b.ToTable("HoaDonDoAnVat", (string)null);
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.KhuyenMai", b =>
                {
                    b.Property<int>("MaKhuyenMai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_khuyen_mai");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhuyenMai"));

                    b.Property<decimal?>("DonHangToiThieu")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("don_hang_toi_thieu");

                    b.Property<decimal>("GiaTriGiam")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gia_tri_giam");

                    b.Property<decimal?>("GiamToiDa")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("giam_toi_da");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hinh_anh");

                    b.Property<string>("LoaiGiamGia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("loai_giam_gia");

                    b.Property<string>("MaCodeGiamGia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_code_giam_gia");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bat_dau");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("date")
                        .HasColumnName("ngay_ket_thuc");

                    b.Property<string>("PhanLoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phan_loai");

                    b.Property<string>("TenKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_khuyen_mai");

                    b.HasKey("MaKhuyenMai");

                    b.ToTable("KhuyenMai", (string)null);
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<int>("DiemTichLuy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("diem_tich_luy");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ho_ten");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int")
                        .HasColumnName("ma_vai_tro");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mat_khau");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaVaiTro");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.Phim", b =>
                {
                    b.Property<int>("MaPhim")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_phim");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhim"));

                    b.Property<string>("Poster")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("poster");

                    b.Property<string>("TenPhim")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_phim");

                    b.Property<string>("TheLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("the_loai");

                    b.Property<int>("ThoiLuong")
                        .HasColumnType("int")
                        .HasColumnName("thoi_luong");

                    b.Property<string>("TomTat")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tom_tat");

                    b.Property<string>("TrangThaiPhim")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Sắp chiếu")
                        .HasColumnName("trang_thai_phim");

                    b.HasKey("MaPhim");

                    b.ToTable("Phim", (string)null);
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.PhongChieu", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_phong");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhong"));

                    b.Property<string>("LoaiPhong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("loai_phong");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_phong");

                    b.HasKey("MaPhong");

                    b.ToTable("PhongChieu", (string)null);
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.SuatChieu", b =>
                {
                    b.Property<int>("MaSuatChieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_suat_chieu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSuatChieu"));

                    b.Property<string>("DinhDang")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("dinh_dang");

                    b.Property<decimal>("GiaVeGoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("gia_ve_goc");

                    b.Property<int>("MaPhim")
                        .HasColumnType("int")
                        .HasColumnName("ma_phim");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int")
                        .HasColumnName("ma_phong");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_gian_bat_dau");

                    b.HasKey("MaSuatChieu");

                    b.HasIndex("MaPhim");

                    b.HasIndex("MaPhong");

                    b.ToTable("SuatChieu", (string)null);
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_vai_tro");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_vai_tro");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTro", (string)null);

                    b.HasData(
                        new
                        {
                            MaVaiTro = 1,
                            TenVaiTro = "Admin"
                        },
                        new
                        {
                            MaVaiTro = 2,
                            TenVaiTro = "Staff"
                        },
                        new
                        {
                            MaVaiTro = 3,
                            TenVaiTro = "Customer"
                        });
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.Ve", b =>
                {
                    b.Property<int>("MaVe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_ve");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVe"));

                    b.Property<decimal>("GiaVe")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gia_ve");

                    b.Property<int>("MaGhe")
                        .HasColumnType("int")
                        .HasColumnName("ma_ghe");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int")
                        .HasColumnName("ma_hoa_don");

                    b.Property<string>("MaQR")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ma_qr");

                    b.Property<int>("MaSuatChieu")
                        .HasColumnType("int")
                        .HasColumnName("ma_suat_chieu");

                    b.Property<string>("MaVaoCong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_vao_cong");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaVe");

                    b.HasIndex("MaGhe");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaSuatChieu", "MaGhe")
                        .IsUnique()
                        .HasFilter("[trang_thai] <> N'Đã hủy'");

                    b.ToTable("Ve", (string)null);
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.DanhGia", b =>
                {
                    b.HasOne("AlphaCinema.Core.Entities.NguoiDung", "NguoiDung")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlphaCinema.Core.Entities.Phim", "Phim")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaPhim")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("Phim");
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.Ghe", b =>
                {
                    b.HasOne("AlphaCinema.Core.Entities.PhongChieu", "PhongChieu")
                        .WithMany("Ghes")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhongChieu");
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.HoaDon", b =>
                {
                    b.HasOne("AlphaCinema.Core.Entities.KhuyenMai", "KhuyenMai")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKhuyenMai")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AlphaCinema.Core.Entities.NguoiDung", "NguoiDung")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhuyenMai");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.HoaDonDoAnVat", b =>
                {
                    b.HasOne("AlphaCinema.Core.Entities.DoAnVat", "DoAnVat")
                        .WithMany("HoaDonDoAnVats")
                        .HasForeignKey("MaDoAnVat")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlphaCinema.Core.Entities.HoaDon", "HoaDon")
                        .WithMany("HoaDonDoAnVats")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoAnVat");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.NguoiDung", b =>
                {
                    b.HasOne("AlphaCinema.Core.Entities.VaiTro", "VaiTro")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.SuatChieu", b =>
                {
                    b.HasOne("AlphaCinema.Core.Entities.Phim", "Phim")
                        .WithMany("SuatChieus")
                        .HasForeignKey("MaPhim")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlphaCinema.Core.Entities.PhongChieu", "PhongChieu")
                        .WithMany("SuatChieus")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Phim");

                    b.Navigation("PhongChieu");
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.Ve", b =>
                {
                    b.HasOne("AlphaCinema.Core.Entities.Ghe", "Ghe")
                        .WithMany("Ves")
                        .HasForeignKey("MaGhe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlphaCinema.Core.Entities.HoaDon", "HoaDon")
                        .WithMany("Ves")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlphaCinema.Core.Entities.SuatChieu", "SuatChieu")
                        .WithMany("Ves")
                        .HasForeignKey("MaSuatChieu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ghe");

                    b.Navigation("HoaDon");

                    b.Navigation("SuatChieu");
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.DoAnVat", b =>
                {
                    b.Navigation("HoaDonDoAnVats");
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.Ghe", b =>
                {
                    b.Navigation("Ves");
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.HoaDon", b =>
                {
                    b.Navigation("HoaDonDoAnVats");

                    b.Navigation("Ves");
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.KhuyenMai", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.NguoiDung", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.Phim", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("SuatChieus");
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.PhongChieu", b =>
                {
                    b.Navigation("Ghes");

                    b.Navigation("SuatChieus");
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.SuatChieu", b =>
                {
                    b.Navigation("Ves");
                });

            modelBuilder.Entity("AlphaCinema.Core.Entities.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
